### ISSUE TITLE
Side-by-side shelter comparison

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#86] opened 2022-09-12 15:59 UTC
Enable selection of 2 or 3 shelters and the assessment results of these shelters to be presented side-by-side (similar to product comparisons in commerce websites). Would require shelters to be selected from the project list page. Perhaps a button for "compare shelters", which then brings up check-boxes to selected 2 or 3 projects for comparison.

Enable download of a standard pdf report of the comparison.

- [ ] Design screenshot/function of the selection @andreullal 
- [ ] Design screenshots of the comparison @andreullal 
- [ ] Design output report @andreullal 
- [ ] Implement

**Comment by guilbep** [comment] 2022-11-08 15:26
closed because duplicate of #120

**Closed by guilbep** 2022-11-08 15:26 UTC
Labels: enhancement, shelter, in design
