### ISSUE TITLE
[FEATURE] <GHG Report generation>

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/unhcr-geneva-tech-hub-app#77] opened 2022-09-12 12:06 UTC
@ctobin111 - can you describe the contents you'd expect (with template layout ideally) for the report ?

**Comment by guilbep** [comment] 2023-01-19 10:37
I'm closing this issue, because all of the above questions were answered here: https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/85 #85

**Comment by charlottegiseleweil** [comment] 2023-03-09 10:08
@ctobin111

**Comment by ctobin111** [comment] 2023-03-09 10:22
@charlottegiseleweil and @guilbep The UNHCR energy and WASH technical groups do not yet have a clear idea on how they want report generation. Ideally they can print the results page. I will come back to this issue  @ctobin111

**Comment by guilbep** [comment] 2023-11-14 09:44
duplicate of #277 closing

**Closed by guilbep** 2023-11-14 09:44 UTC
Labels: feat, ghg, in design
