### ISSUE TITLE
[FEATURE] <GHG: Diesel Generators, go from KV to KwH with a power factor>

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#594] opened 2023-12-20 14:04 UTC
@guilbep We discussed going from kV to kWh as an option for diesel generators.

A power factor is required and a standard power factor is generally 0.8. Source: [https://www.globalpwr.com/power-calculator/]

Here is the equation:

kVA * PF (Power factor) = kW

![image](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/111510926/ed24ec9e-0de6-4660-85df-ec7ef4552c95)

**Comment by guilbep** [comment] 2023-12-22 15:00
duplicate of #585

**Closed by guilbep** 2023-12-22 15:00 UTC
Labels: feat, ghg
