### ISSUE TITLE
[FEATURE] <GHG: Printing of results> #576

### ISSUE THREAD

**Issue by ctobin111** [EPFL-ENAC/unhcr-geneva-tech-hub-app#576] opened 2023-11-14 11:01 UTC
@guilbep Can there be an option to print the results into a pdf. Results per module and the overall results?

Ideally, it would work like the Shelter App, where there would be a button, "Print Assessment Report" that can print the final results and any module specific results. Ideally, they can choose which module results they would like to print. Not every module will want to be printed by each user (some are WASH experts, some energy experts).

**Comment by guilbep** [comment] 2023-12-18 10:08
duplicate of #591 done in #591

**Closed by guilbep** 2023-12-18 10:08 UTC
Labels: triage
