### ISSUE TITLE
[BUG] <Scorecard not populated - projects all incomplete>

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#640] opened 2024-03-18 16:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Projects are noted as incomplete, even when all of the items are filled. Seems to have something to do with the background-calculated criteria, such as ventilation (ratio floor area to window area).
<img width="1567" alt="Screenshot 2024-03-18 at 15 52 38" src="https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/1e68a86f-652d-46b7-a2b5-cf4957819540">
![Screenshot 2024-03-18 at 17 16 23](https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/assets/108796343/cf4c8c8b-2e17-421d-ba1f-86f6d186f4c6)

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by guilbep** [comment] 2024-03-24 21:21
duplicate of https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/604 and https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/618

There was some 'behavior' not behaving properly maybe. I added some code to make the transition easier. Let's see if it brakes some things or not

**Closed by guilbep** 2024-03-24 21:21 UTC
Labels: bug, shelter, triage

**Comment by guilbep** [comment] 2024-03-24 21:23
done in [dev 00685d0b] fix(frontend): try to avoid weird behavior with shelter #640
